### ISSUE TITLE
Theoretical question regarding the index

### ISSUE THREAD

**Issue by ctlaltdefeat** [philipl/pifs#10]
Is it known (or, technically, hypothesized) what is the expected value of the index in pi of a given, random sequence of n bits? After all, if the logarithm of the index (i.e number of bits in index) grows linearly in the number of bits being stored, then storing the metadata is perhaps just as expensive as storing the data itself.

**Comment by chrismwendt** [comment]
> what is the expected index of a random sequence of n digits (or bits), in a countable random sequence of digits

The expected index is `2^n` (which takes `n` bits to represent) because the indexes are geometrically distributed with probability `1/(2^n)` (the probability that a file exists at a given index) and the mean of a geometric distribution is `1/p = 1/1/(2^n) = 2^n`. For more info, see my blog post https://chrismwendt.github.io/blog/2018/03/18/analysis-of-pifs-compression.html
